### ISSUE TITLE
Doesn't work at all here

### ISSUE THREAD

**Issue by Neo-29** [demiskp/custom-accent-colors#1]
- Gnome 43
- archlinux

No result

**Comment by demiskp** [comment]
can you send a pic of the error message?

**Comment by Neo-29** [comment]
There's no error message.
The extension works but nothing changes when applying colors...

**Comment by demiskp** [comment]
I just installed the extension in an arch vm and it seems to work fine, did you log out and back in after changing the color?

**Comment by Neo-29** [comment]
Yes

**Comment by Neo-29** [comment]
Shell menu still blue.

**Comment by demiskp** [comment]
have you changed the shell theme to CustomAccentColors?

**Comment by Neo-29** [comment]
How do? Read that but don't have a clue of how to do so. Not clear enough.

**Comment by demiskp** [comment]
in arch the user themes extension is pre installed so you can set it from gnome tweaks

**Comment by demiskp** [comment]
in appearance -> shell

**Comment by Neo-29** [comment]
Ohhhhh... Right... It's in tweaks. I see.. I may retry and let you know

**Comment by Neo-29** [comment]
Works like a charm. Tks.
I close
