### ISSUE TITLE
Gnome-shell theming doesnt work

### ISSUE THREAD

**Issue by Radical4ever** [demiskp/custom-accent-colors#14]
hi, so basically there is no gnome shell theme and when i try some sort of forced way i end up with this:
![Captura desde 2023-03-31 20-42-10](https://user-images.githubusercontent.com/83252104/229250764-6d832a1a-07ce-4dd8-81f2-eba7e7bb9be0.png)

**Comment by Radical4ever** [comment]
this is gnome 44 btw

**Comment by demiskp** [comment]
this extension doesn't support gnome 44 yet, I'll probably add support for gnome 44 soon.

**Comment by Radical4ever** [comment]
Ok then, thanks for aswering, ill close the issue for now i guess

**Comment by OlegKrikun** [comment]
@dimitriskp22 Thanks a lot for adding gnome 44 support ❤️

**Comment by dimitriskp22** [comment]
@OlegKrikun you're welcome :) , if everything goes well I'll probably release v6 next week, unfortunately the [user themes](https://extensions.gnome.org/extension/19/user-themes/) extension, that is required for the shell theming to work, doesn't seem to officially support gnome 44 yet, but at least distros like fedora and arch ship a version of the user themes extension that supports gnome 44 in their repos.

**Comment by OlegKrikun** [comment]
I wrote my message after I tested the latest changes =)

**Comment by harpreetsb** [comment]
still not working

**Comment by dimitriskp22** [comment]
@harpreetsb did you installed the extension from extensions.gnome.org? also make sure you have the Shell Theme set to custom-accent-colors in gnome tweaks

**Comment by major-mayer** [comment]
For me the problem was that this extension wasn't activated and the shell theme was set to "CustomAccentColors" instead of "Custom-Accent-Colors" (probably a leftover from an older version of this extension).
After I re-activated the extension and set the correct shell theme, the visual bugs were gone again.
