### ISSUE TITLE
Majaro, blue is green

### ISSUE THREAD

**Issue by zazou99vlc** [demiskp/custom-accent-colors#15]
The extension offers 9 colors, but the files (gnome-shell.css) generated by the extension are 8 because Blue (default) is supposed to be blue, but in Manjaro with Gnome 43 this color is the green of MAIA so it turns green.

**Comment by dimitriskprs** [comment]
hey @zazou99vlc, that sounds more like a problem with manjaro's version of the extension, so unfortunately I can't help.

**Comment by zazou99vlc** [comment]
Yes, I have solved it, installing gnome-manjaro-vanilla and running cleanup-manjaro-gnome which is a part of this package and blue has returned :) Thank you
