### ISSUE TITLE
After this extension Gradience doesnt working

### ISSUE THREAD

**Issue by DiamivaeBro** [demiskp/custom-accent-colors#20]
I uninstalled this extension,but but still Gradience doesn't work

**Comment by dimitriskprs** [comment]
The extension should remove all the customizations it did when it's deactivated or uninstalled. Maybe you can try to manually remove the "gtk.css" files in the ~/.config/gtk-3.0/ and ~/.config/gtk-4.0/ directories (if they exist) and the "Custom-Accent-Colors" directory in the ~/.local/share/themes/ directory (if it exist), you can also try to open the Flatseal app and Reset the permissions in "All Applications". If you do all these steps and the problem with Gradience still exists, then it's probably a problem unrelated to the extension.

**Comment by DiamivaeBro** [comment]
It helped,thanks!
