### ISSUE TITLE
Feature Request: Add folders icons that follow the selected accent color

### ISSUE THREAD

**Issue by racsuline** [demiskp/custom-accent-colors#22]
A recent project by @AtiusAmy has been developed, which basically provides adwaita folder icons (and the nautilus icon) that align with the accent colors of this extension. I am curious if there is a chance of integrating this icon theme like a feature for this extension

https://github.com/AtiusAmy/AdwaitaColors

**Comment by dimitriskprs** [comment]
this project looks very nice! unfortunately I don't have the time to implement and test this feature right now.
