### ISSUE TITLE
(enhancement) Use Yellow 5 instead of Yellow 4

### ISSUE THREAD

**Issue by heschy2** [demiskp/custom-accent-colors#27]
The GNOME-Shell itself currently uses dark mode, regardless of the users preferences, so it is kind of necessary to make sure the theme looks good in dark mode, and the yellow one is currently not looking good, because the yellow is to light to be used as the background for white Text. Also, people who use dark mode do have this problem not only in the shell, but also in other apps, so you should use a dark yellow. You currently use the second-darkest yellow, but it is still to light, so I would consider switching to Yellow 5 (e5a50a) wich is the darkest yellow available in the GNOME HIG. This request is like #7 but for yellow. 

Thank you in advance!

**Comment by dimitriskprs** [comment]
Hey @heschy2 , the yellow accent color is indeed a bit too light, in the next update I plan to change more colors than just that, but unfortunately I don't have the time to do it right now. That's also why the colored folders feature hasn't made it into the gnome extensions website version of the extension yet, it increases the extension's filesize by a lot and I currently don't have the time to find a way to make the filesize smaller.
