### ISSUE TITLE
where is the light theme support?

### ISSUE THREAD

**Issue by hoshi411** [demiskp/custom-accent-colors#29]
It only works with dark themes.

**Comment by dimitriskprs** [comment]
hey @hoshi411 , if by "light theme" you're referring to the light version of the default gnome shell theme, provided by the "Light Style" extension, that is not officially supported by the gnome project yet, and it's not supported by my extension either (yet).

**Comment by UlyssesZh** [comment]
It would be nice to support the light theme.
