### ISSUE TITLE
[QUESTION] Is it possible to appear on the settings page?

### ISSUE THREAD

**Issue by radical4ever** [demiskp/custom-accent-colors#3]
Hi, so is it possible to an extension to appear on a default gnome app as a setting, so we could easily acces our accent color set on the settings page, like elementary os?. Thank you

**Comment by dimitriskprs** [comment]
hey :), unfortunately that is not possible because as far as I know the stock Gnome Settings app can't interact with extensions.

**Comment by radical4ever** [comment]
Oh well.. guess i close the issue. The extension is very good on its own, it saves me a lot of time changing the accent color. Thanks for the extension and for answer my question!
