### ISSUE TITLE
[ MORE COLORS ] I want a "teal color" shell theme

### ISSUE THREAD

**Issue by jit-x** [demiskp/custom-accent-colors#35]
tela icons, papirus icons and many other icon themes have teal folders which look great but I want a teal theme so that I can use the teal version of most of the icon packs... also ubuntu's yuru has a teal shell theme so as I use Arch I miss the teal shell

**Comment by dimitriskprs** [comment]
I try to only use colors from the official gnome color palette and there's no teal color in it, so that can't be done currently.

**Comment by jit-x** [comment]
Consider adding Green 4 or 5 then...
