### ISSUE TITLE
Not compatible with GNOME 46

### ISSUE THREAD

**Issue by mahtosujeet** [demiskp/custom-accent-colors#37]
The GNOME Shell Extensions website and GNOME Extensions app say that it's out of date.

**Comment by dimitriskprs** [comment]
hey @MahtoSujeet , I just started working on Gnome 46 support, if everything goes as planed, the new version is going to be ready in the coming days :)

**Comment by mahtosujeet** [comment]
Update is live in GNOME shell extensions website. Everything is working.
Thank you very much.
