### ISSUE TITLE
The border of some input fields don't get styled with the chosen accent color on Gnome 46

### ISSUE THREAD

**Issue by timoschroeder1213** [demiskp/custom-accent-colors#38]
I have chosen Maia as accent color. When a dialog comes up for entering credentials or when I activate the input field on the application overview, the borders of the input fields aren't styled with the chosen accent color anymore on Gnome 46.

![Bildschirmfoto vom 2024-04-05 10-28-56](https://github.com/dimitriskp22/custom-accent-colors/assets/89973985/61370c9a-9a3c-4771-ac1e-58de0db35ecd)

![Bildschirmfoto vom 2024-04-05 10-28-04](https://github.com/dimitriskp22/custom-accent-colors/assets/89973985/37f9b995-4a0b-46e6-97ed-e1b02cacb0e3)

**Comment by dimitriskprs** [comment]
Hey @timoschroeder1213, there's no "Maia" option in my extension. You're probably using an unofficial patched version (perhaps the one that comes preinstalled in Manjaro Linux?). The official version of the extension (from extensions.gnome.org) seems to be working just fine on GNOME OS and Fedora Rawhide.

**Comment by timoschroeder1213** [comment]
I wasn't aware that Manjaro is shipping a patched version. I checked with another color and it's working fine. Sorry for having bothered you. And thank you for this extension!

**Comment by dimitriskprs** [comment]
don't worry, you didn't bother me at all :) , it would also be a good idea to get in contact with the manjaro team and let them know about this issue.
