### ISSUE TITLE
[Feature Request] Change folder color

### ISSUE THREAD

**Issue by yochananmarqos** [demiskp/custom-accent-colors#4]
Would it be possible to change the folder color at the same time the accent color is changed? This could be accomplished using [paprius-folders](https://github.com/PapirusDevelopmentTeam/papirus-folders) with the[ papirus-icon-theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme).

**Comment by dimitriskprs** [comment]
I guess it could be done (I don't have the time to do it rn though). I also don't like the idea of using 3rd party icons, so if I ever implement this feature I'll probably use a recolored version of the default adwaita folder icons.

**Comment by yochananmarqos** [comment]
Sure, no worries. Just an idea.
