### ISSUE TITLE
The shell theme moves the active application dot up onto the icon

### ISSUE THREAD

**Issue by dylankird** [demiskp/custom-accent-colors#40]
This is what my icons look like now (using the custom accent colors shell theme):
![image](https://github.com/demetrisk03/custom-accent-colors/assets/50091049/39518a65-70b3-48c2-89ef-3729506e60c1)

This is the expected behavior:
![image](https://github.com/demetrisk03/custom-accent-colors/assets/50091049/dff1ae7a-032b-4546-9db3-851e2bb74cca)

I am on Arch Linux using gnome-shell 1:46.2-1.

Here's a bit more system info: 
![image](https://github.com/demetrisk03/custom-accent-colors/assets/50091049/78288db3-0869-4ce2-8869-7e858ef88dd0)

I'm not sure what changed to have this happen, but I just noticed today. I tried reinstalling the extension, but no luck. If there is anything I should try and anything I can do to help, please let me know.

**Comment by dimitriskprs** [comment]
It's probably caused by the new 46.2 version, I'm working on fixing it :)

**Comment by dimitriskprs** [comment]
version 11 that includes the fix for Gnome 46.2 is now available on extensions.gnome.org, if you still encounter problems after updating try restarting the extension or restarting the gnome shell :)

**Comment by dylankird** [comment]
It is fixed! Thanks so much :)
