### ISSUE TITLE
Some colors are now available in Gnome 46 - Fedora

### ISSUE THREAD

**Issue by s4rs-c0v2** [demiskp/custom-accent-colors#41]
Hi,
I found that some colors are not longer available in Fedora40 Gnome 46. Grey is missing. Any option to bring it back?

**Comment by dimitriskprs** [comment]
hey @s4rs-c0v2, unfortunately the gray color didn't have enough contrast and was causing problems for a lot of people, so after getting a lot of bug reports for that color I decided to remove it, I also changed most of the colors to improve their contrast too.

**Comment by s4rs-c0v2** [comment]
it was the nicest color for me xD, thanks for swift response

**Comment by s4rs-c0v2** [comment]
Thank you
