### ISSUE TITLE
Accent Color Not Applying to Top Bar

### ISSUE THREAD

**Issue by Adisk06** [demiskp/custom-accent-colors#42]
Description:

The accent color seems to have changed everywhere except for the top bar, as seen in the image below:

![Schermata del 2024-06-14 19-46-25](https://github.com/demetrisk03/custom-accent-colors/assets/94019983/21d4c943-2d6f-46b0-a1c7-8940f255d0bf)

Steps to reproduce:

1.    Change the accent color in the settings.
2.    Observe that the accent color updates across various elements. (after reboot/restarting the session)
3.    Notice that the top bar retains the old color.

Expected behavior:
The accent color should update uniformly across all UI elements, including the top bar.

Actual behavior:
The top bar retains the previous color even after the accent color is changed.

**Comment by Adisk06** [comment]
Additional Information:

I forgot to mention that I am using GNOME 46 on Fedora with Custom Accent Colors version 11 installed from the GNOME Extensions website.

**Comment by dimitriskprs** [comment]
hey @Adisk06 have you set the shell theme to custom-accent-colors in gnome tweaks as the button subtitle says? you might also need to relogin after choosing your prefered accent color as the accent color subtitle says.

**Comment by videoMonkey** [comment]
> hey @Adisk06 have you set the shell theme to custom-accent-colors in gnome tweaks as the button subtitle says? you might also need to relogin after choosing your prefered accent color as the accent color subtitle says.

Hey! That fixed it. I don't know why I didn't see this sooner.
