### ISSUE TITLE
What does the "Flatpak Theming" option do?

### ISSUE THREAD

**Issue by korpe1** [demiskp/custom-accent-colors#43]
What does the "Flatpak Theming" option do? I mean, accent colours are represented in the universal Portals API which native, Flatpak, etc. apps can always use if they want. So, why dedicated option for Flatpak?

**Comment by dimitriskprs** [comment]
This extension doesn't use the Portal API, which was created recently. Instead, it works similarly to Gradience by modifying the gtk.css file in the config directory. The Flatpak theming option gives all Flatpak apps read access to that file.

**Comment by korpe1** [comment]
Okay, so this extension doesn't use portal API at all :(

> The Flatpak theming option gives all Flatpak apps read access to that file.

Does it use the flatpak cli API? For example something like `flatpak override --user --filesystem=xdg-config/gtk-4.0`?

**Comment by dimitriskprs** [comment]
yes, you can take a look at the source code to see exactly how it works :)
