### ISSUE TITLE
Possibility to add custom colours? 

### ISSUE THREAD

**Issue by Geek1405** [demiskp/custom-accent-colors#45]
I like the adwaita theme, but I also like a very particular colour, i don't think it's in Gnome's palette, so I won't ask you to add an option for some random colour, but I was wondering if it were possible to add an option for custom colours, with maybe a warning if the colours don't line up with gnome's palette? I'm not even sure if this is possible, thank you for any response.

**Comment by dimitriskprs** [comment]
hey @Geek1405, unfortunately for each additional accent color supported by this extension, a corresponding GNOME Shell theme must be included for the shell theming functionality to work. This means arbitrary accent colors are not possible.

**Comment by Geek1405** [comment]
that's a shame, thanks for the confirmation.
