### ISSUE TITLE
GDM support?

### ISSUE THREAD

**Issue by luciofstars** [demiskp/custom-accent-colors#46]
Any way to have this affect the login screen (GDM)?

**Comment by dimitriskprs** [comment]
hey @skyeforeverblue, unfortunately as far as I know, gdm can not be modified by gnome shell extensions, since it's a separate component from the gnome shell.

**Comment by luciofstars** [comment]
I actually just got it working this morning @demetrisk03 . I had to copy the theme to /usr/share/themes/ and enable it with [`gdm-settings`](https://github.com/gdm-settings/gdm-settings). Feel free to add this to the README or relevant place.

**Comment by dimitriskprs** [comment]
I know about the ability to manually change gdm themes, but that would require the user to manually copy-paste the shell theme to /usr/share/themes every time they choose another accent color... I also don't like the idea of encouraging people to mess with system-wide files outside their home directory.
