### ISSUE TITLE
Wallpaper Support

### ISSUE THREAD

**Issue by NiffirgkcaJ** [demiskp/custom-accent-colors#47]
Good day! I would like to ask, since GNOME plans to do some custom user colouring of the desktop's accent colours, would it be possible for this extension to at least copy colours from the wallpaper or to at least allow more custom RGB colours beyond what GNOME plans to add in GNOME 47?

**Comment by dimitriskprs** [comment]
hey @NiffirgkcaJ, unfortunately allowing users to choose arbitrary colors would be impossible due to the way the shell theming functionality is implemented.

**Comment by NiffirgkcaJ** [comment]
> hey @NiffirgkcaJ, unfortunately allowing users to choose arbitrary colors would be impossible due to the way the shell theming functionality is implemented.

Oh, okay! Thanks for answering, though.
