### ISSUE TITLE
GNOME 47 support

### ISSUE THREAD

**Issue by radical4ever** [demiskp/custom-accent-colors#48]
Hi, so in gnome 47 accent colors were introduced, they work to apps with the proper support, but not all of them have it and gtk3 apps cant, it will be cool if the app gets updated to support gnome 47 alongside its default colors, thank you

**Comment by dimitriskprs** [comment]
you're right, but syncing accent colors between the (recently officially added) accent colors of the gnome-shell and the adw-gtk3 theme, is different from the original goal of the extension, which was to add accent colors to the gnome-shell, so maybe a separate extension needs to be made for the feature you're requesting.

**Comment by radical4ever** [comment]
Then I guess adding only the colors of the official gnome accents colors to the extension is fine too, I think with only that the extension could be for making adw-gtk3 use the os main accent color, since the theme itself is unable to do that

**Comment by dimitriskprs** [comment]
I agree, I just don't think that I like the idea of changing the whole purpose of the current extension (as I said above), in the future I might make a new extension with a more appropriate name, for the purpose you're describing above.

**Comment by radical4ever** [comment]
It's okay, this was a suggestion, but this extension still rocks in 47 since gtk3 accent coloring is impossible if not by this extension

**Comment by linux-universe** [comment]
> you're right, but syncing accent colors between the (recently officially added) accent colors of the gnome-shell and the adw-gtk3 theme, is different from the original goal of the extension, which was to add accent colors to the gnome-shell, so maybe a separate extension needs to be made for the feature you're requesting.

I would love to see this
