### ISSUE TITLE
Feature Request: Add the new teal/dark greenish color (the second one in the screenshot) that was introduced in Gnome 47 accent colors

### ISSUE THREAD

**Issue by n3thshan** [demiskp/custom-accent-colors#49]
![Screenshot from 2024-09-21 23-24-31](https://github.com/user-attachments/assets/3c83e77a-561d-4aba-8b4f-d371ed9c84f3)

Gnome 47 stable did release but its accent colors system isnt as robust (or whatever more suitable term) as this extension because it does not theme gtk3 apps and flatpak apps that use >47 runtime. Even so, by the time fedora 41 releases, both those issues would probably be fixed. However, till then, which is I think November 5th, most users including me will have to stick with gnome 46 and I would like you to consider implementing this color and/or even other colors that are not there currently in this extension that was introduced in gnome 47. I know you are concerned about Gnome's color palette so here you go: official colors from Gnome themselves. Thanks for your attention!

**Comment by dimitriskprs** [comment]
hey @n3thshan, your idea is nice, but at the same time I'm not sure that it's worth it to update the accent colors again, since the current ones work fine and as you said, Gnome 47 will be available in most major distros in a couple of weeks :)

**Comment by hzmaya** [comment]
@demetrisk03 yes, Gnome 47 added accent colors but, it is not feature complete as yours since Gnome's implementation can't affect anything but libadwaita apps.

**Comment by dimitriskprs** [comment]
@hzmaya, I understand what you're saying, but now that the gnome shell has accent color support their implementation might overlap with the one from the extension, causing broken behavior... also their implementation is much better than my extension's, since it's using the official accent color portal, instead of using css which is what my extension is using.
