### ISSUE TITLE
Where do I get the shell theme???

### ISSUE THREAD

**Issue by Anikmoujegy** [demiskp/custom-accent-colors#5]
As I installed the extension it says to theme the shell I have to installed CustomAccentColor theme first but where would I get get it......

**Comment by demiskp** [comment]
the theme is automatically placed in the ~/.local/share/themes dir when you turn on the "Shell Theming" Switch, and you just have to enable it with the gnome-tweaks app. I'll probably change the description under the switch to something clearer in the next version.

**Comment by Anikmoujegy** [comment]
ok thanks
