### ISSUE TITLE
Theme exists after extetnsion is deleted

### ISSUE THREAD

**Issue by jasursadikov** [demiskp/custom-accent-colors#50]
After latest GNOME updated, I have decided to remove the extension,  but I still have custom-accent-colors in my Tweaks:
![image](https://github.com/user-attachments/assets/1b3ff4fe-6f14-4cd3-a434-90e968a92d87)

**Comment by dimitriskprs** [comment]
since you're not using the extension anymore, you can remove the theme and change the shell theme back to default in tweaks

**Comment by jasursadikov** [comment]
Yes, but why do I still have this option?
![image](https://github.com/user-attachments/assets/dd440346-2f23-4a5e-9eae-38d8f1a278b9)

**Comment by dimitriskprs** [comment]
because you haven't remove the shell theme from the themes directory (aka ~/.local/share/themes)

**Comment by jasursadikov** [comment]
I do not even have this directory :)
![image](https://github.com/user-attachments/assets/5b2d44ed-5039-4b3c-a9b9-5084489563c5)

**Comment by dimitriskprs** [comment]
every user's themes directory is in his home directory (~/.local/share/themes), /usr/share/themes is for system-wide themes, btw I misplaced the dot in my previous comment, I now edited it, sorry :)

**Comment by jasursadikov** [comment]
Yeah! Sorry, my bad as well that I haven't seen that :D
Thank you! And thank you for your extension, that was my pleasure to use it!
