### ISSUE TITLE
The chosen theme is not applied on the login screen (gdm)

### ISSUE THREAD

**Issue by RogerioTDS** [demiskp/custom-accent-colors#6]
Do you have any way to apply the chosen theme on the login screen(gdm)? Because the chosen theme does not apply in gdm. There, in gdm, it retains the default color of gnome (blue).
![gdm](https://user-images.githubusercontent.com/120617835/213029004-6e0da746-3197-4906-bf55-af52e7cee5e2.jpg)
![gdm2](https://user-images.githubusercontent.com/120617835/213029009-afeb7142-bcb0-44ef-a365-4d1944fddcff.jpg)
![gnome_shell](https://user-images.githubusercontent.com/120617835/213029053-9f864404-1c31-48e5-bd0b-4b787d9ee1bc.png)

**Comment by demiskp** [comment]
I don't think there's a way to modify the gdm theme with a gnome shell extension, because gdm is a display manager.

**Comment by RogerioTDS** [comment]
OK.
Thanks!
